# Generated by Django 2.1.4 on 2019-06-25 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0002_badges_elite_leader_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='badges',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abp.Badges'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='elite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abp.Elite'),
            preserve_default=False,
        ),
    ]
