# Generated by Django 2.1.4 on 2019-06-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0004_battle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='leader',
            new_name='battling_leader',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='trainer',
            new_name='battling_trainer',
        ),
    ]
