# Generated by Django 2.1.4 on 2019-06-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0005_auto_20190625_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='battles',
            field=models.ManyToManyField(to='abp.Battle'),
        ),
    ]
