# Generated by Django 2.1.4 on 2019-06-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0009_auto_20190625_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='elite',
        ),
    ]
