# Generated by Django 2.1.4 on 2019-06-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0013_remove_trainer_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='reference',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Rock', 'Rock'), ('Electric', 'Electric'), ('Ghost', 'Ghost'), ('Ice', 'Ice'), ('Poison', 'Poison'), ('Water', 'Water'), ('Dark', 'Dark'), ('Grass', 'Grass'), ('Dragon', 'Dragon')], max_length=9, null=True, unique=True),
        ),
    ]
