# Generated by Django 2.1.4 on 2019-06-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0017_auto_20190626_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='num_badges',
        ),
        migrations.AddField(
            model_name='leader',
            name='pokemon_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Rock', 'Rock'), ('Electric', 'Electric'), ('Ghost', 'Ghost'), ('Ice', 'Ice'), ('Poison', 'Poison'), ('Water', 'Water'), ('Dark', 'Dark'), ('Grass', 'Grass'), ('Dragon', 'Dragon'), ('Bug', 'Bug'), ('Steel', 'Steel'), ('Fire', 'Fire'), ('Fairy', 'Fairy')], default='', max_length=9, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='role',
            field=models.CharField(choices=[('Gym Leader', 'Gym Leader'), ('Elite Four', 'Elite Four'), ('Champion', 'Champion')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
