# Generated by Django 2.1.4 on 2019-06-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0018_auto_20190627_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='pokemon_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Rock', 'Rock'), ('Electric', 'Electric'), ('Ghost', 'Ghost'), ('Ice', 'Ice'), ('Poison', 'Poison'), ('Water', 'Water'), ('Dark', 'Dark'), ('Grass', 'Grass'), ('Dragon', 'Dragon'), ('Bug', 'Bug'), ('Steel', 'Steel'), ('Fire', 'Fire'), ('Fairy', 'Fairy')], max_length=9, null=True, unique=True),
        ),
    ]
