# Generated by Django 2.1.4 on 2019-06-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abp', '0019_auto_20190627_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
    ]
