# Generated by Django 2.1.4 on 2019-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3po', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c3poquote',
            name='is_not_sure',
            field=models.BooleanField(default=False),
        ),
    ]
