# Generated by Django 2.1.4 on 2019-07-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GomezQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=900)),
                ('quote_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
